_includes/global_nav.html
assets/css/static-main.css

- Set global nav menu items to "active" based on the page you are viewing. A minor UX improvement meant to indicate the page/section of the site you are currently on.
These changes are related to the on-going initiative to move sandbox and production user guide documentation to a unified location. A security checklist has been completed to evaluate the implications of redirecting the sandbox user guide to the combined sandbox/prod user guide (linked below).
- See: https://confluence.cms.gov/pages/viewpage.action?pageId=154444934
Please review by checking out this branch and running the site as described in the [README](https://github.com/CMSgov/bcda-static-site/blob/master/README.md).
Examples of the UI behavior:
**When viewing the home/landing page**
**When viewing the Production …

BCDA-1717: Set nav menu items to "active" based on the current page

---

.github/pull_request_template.md

Noticed that the PR template in this repository is out of date. This change updates the template to be inline with what we use on our other repositories.
These changes are not related to a security concern in particular, but generally to how the team thinks about security processes and workflows.
Feedback of any sort is welcome, though this PR is mostly intended to bring the bcda-static-site repo's pull request template into sync with what's in-use on bcda-app. Please see the discussion in the comments on the [original PR](https://github.com/CMSgov/bcda-app/pull/344) for context.

BCDA-1251: Update pull request template

---

ops/github_release.py
ops/release.sh

Allow tag/release process to be executed from Jenkins job in an automated fashion.
- Migrated to this repository existing scripts (used by BCDA and SSAS) for tagging/releasing BCDA static site repository.   Note: all code in this PR has been vetted through tag/release process of BCDA and SSAS.
- Jenkins job developed as part of [this PR](https://github.com/CMSgov/bcda-ops/pull/358).
PII/PHI is not involved in this process.  This is simply automation for tagging in Github.
Jenkins job can be [viewed here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Tag%20and%20Release%20-%20Static%20Site/).
Several releases created for `bcda-static-site`.  See screenshot below. (Note: all temporary tags and releases have since been removed).
Please review.

BCDA-2351: Automate Tag/Release Process for BCDA Static Site

---

sandbox/user_guide.md

We indicate that we provide four sets of synthetic credentials, but we actually provide five sets.
Fixed the trivial typo.
No security implications with this change.
Tested locally.
Please review.

Specify that we provide 5 sets of synthetic credentials.

---

production/technical_userguide.md
sandbox/technical_user_guide.md

Since introducing Akamai, our cURL examples using Basic authentication no longer work.  This affects the `POST /auth/token` endpoint.  To fix this, we need to add an empty body by using a `-d ''` parameter.
- Add a `-d ''` parameter to curl
This change should not affect the security stance of the application, its documentation, or its users.  Note that the screenshots below depict public credentials in the sandbox environment.
- Does any description of the change need to be added to the documentation?
- Would a different order of parameters be more clear?

BCDA-2501 Update cURL examples to work with Akamai

---

_layouts/home.html

We have two `<header>` elements, which violates [best practice](https://dequeuniversity.com/rules/axe/3.3/landmark-no-duplicate-banner) for accessibility.
Change the second `<header>` to a `<div>`
This invisible change should have no security impact.
Would we rather fold the second `<header>` into the first (see ticket for option details)?

BCDA-2300 Accessibility: Change second <header> to <div>

---

_includes/global_nav.html
_includes/header.html
_layouts/home.html

Ideally, navigation elements should be labeled.
- Add an `aria-label` (Primary, Secondary, or Page) to each navigation section
- Change `<div>` to `<nav>` for page navigation
The addition of these largely invisible labels should have no security impact.
Would it be better to have a single `<nav>` around the page navigation section?

BCDA-2303 Accessibility: Follow <nav> best practices

---

_includes/footer.html

Screen readers don't like heading levels to be skipped.  We can adjust our footer to that best practice without visible change.
- Change footer headings to `<h2>`
Any concerns?

BCDA-2299 Accessibility: Avoid skipping heading levels (footer)

---

_includes/footer.html

Explicitly setting the footer to the `contentinfo` role is redundant, as assistive technology will set it automatically.
- Remove the `contentinfo` role in the footer
- Any suggestions?

BCDA-2308 Accessibility: Remove contentinfo role in footer

---

_layouts/home.html

The submenu at the left of the page is too important to get an `<aside>` tag.
- Replace with a `<div>` tag
- Any suggestions welcome

BCDA-2307 Accessibility: Replace <aside> with <div>

---

_includes/header.html

The mobile menu should be activated with a `<button>`, not the current anchor link.
- Change the tag
- Note that the blue highlight at the left of the selected button is new, but may be preferred for accessibility.  Do you disagree?

BCDA-2306 Accessibility: Mobile menu button

---

_includes/global_nav.html

The text in the `aria-label` provided with the top menu items duplicates the link text.  This is repetitive for assistive technology.
Remove `aria-label` tags on the top menu.
Is there any other code or configuration that affects the top menu items?

BCDA-2304 Accessibility: Remove aria-label on top menu

---

_includes/global_nav.html
assets/css/static-main.css

The top menu currently uses `<div>` elements, but should have `<ul>`.
- Move currently duplicated `<nav>` tag to wrap around entire top menu
- Add list elements and required CSS to mimic previous behavior
- Is there a better CSS class name for this purpose?
- Is there a better way to accomplish this?
- Is the slightly wider space between menu items acceptable?

BCDA-2305 Accessibility: Menu uses a list

---

production/user_guide.md
sandbox/user_guide.md

Update to user guide language around Bearer token in swagger
Users have been pasting in tokens to the Value box in Swagger's authorization window without "Bearer " appended in front of them. This PR, along with those that fix BCDA-2716 and BCDA-2717, is the first attempt at applying content strategy to call attention to this requirement.
* Call out more clearly that Bearer is case-sensitive and must be followed by a space
* Describe error that will result if step is done incorrectly
Current state:
* We say "this is critical!" without specifying what "this" is
* No description of resultant error
PR state:
* Provides answers to questions we have seen users have in onboarding sessions (case-sensitivity, need for space)
* Describes resultant error and allows for search/skim behavior for users …

BCDA-2722: update user guide language around Bearer token

---

_includes/copy_snippet.md
sandbox/user_guide.md

Our nifty button to copy client ID's/secrets from the user guide has an accessibility flaw: it has a hidden duplicate input element, to make copying easier.
This PR does away with the input element, and thus the duplication, accepting the challenge goal of the ticket and sidestepping the original request (to add `<label>` tags for the input).
- Change the `copyText()` function to not need an input element
The Javascript function touches security credentials, albeit publicly published credentials.  However, there is no effective change in security posture with the script changes.
Please try this in multiple browsers!

BCDA-2312 Accessibility: Do not duplicate credential elements

---

assets/css/static-main.css
production/technical_userguide.md
sandbox/technical_user_guide.md

- [BCDA-2313](https://jira.cms.gov/browse/BCDA-2313)
- [BCDA-2318](https://jira.cms.gov/browse/BCDA-2318)
- [BCDA-2320](https://jira.cms.gov/browse/BCDA-2320)
- [BCDA-2322](https://jira.cms.gov/browse/BCDA-2322)
At extreme zoom levels, even mid-length URL's require the reader to scroll.  This PR applies wrapping (even mid-"word") to ease zoomed reading.
- Apply word wrapping CSS to `<code>` and `<a>` elements
- Ensure all non-linkable URL's are wrapped in `<code>` elements
No data has changed; just line wrapping.
Do you prefer a different approach?

BCDA-2318 Accessibility: Wrap long URL's

---

production/user_guide.md
sandbox/user_guide.md

- [BCDA-2319](https://jira.cms.gov/browse/BCDA-2319)
- [BCDA-2315](https://jira.cms.gov/browse/BCDA-2315)
Using a screen reader replaces images with the image `alt` text.  Between the text on the page and the `alt` text, a coherent story should be told.  This PR attempts to improve the story for the user guides.
- Detail the key lesson from the image in the `alt` text 
- Use empty `alt` text where the key message has already been said
No new information is being conveyed, and no security boundaries are being crossed.
1. Please read through the user guides without the images.  Does the `alt` text give enough information?
2. Compare each image with its `alt` text.  Are the essential lessons from the image being conveyed?
3. Are there any differences between the `production` and `sandbox` …

BCDA-2319 Accessibility: New alt text for user guide(s)

---

assets/css/static-main.css

Our code blocks need to be readable to those requiring high contrast.  The target contrast ratio is 4.5:1, and we are currently at 3.6:1.
- Choose a similar color for highlighted text blocks that provides a 6.3:1 contrast ratio.
No security principles were harmed in this color selection.
- We have some wiggle room to select a slightly brighter color.  What do you think?

BCDA-2314 Accessibility: Increase code block contrast ratio

---

_layouts/default.html
assets/css/static-main.css
assets/js/code.js

Some readers of our website may be navigating with the keyboard.  We want our code samples to be reachable by this navigation method.
- Add a `tabindex = "0"` property to all `<code>` tags
Option 1: Because we're writing our site in Markdown and converting it to HTML, it would be nice if we could make a simple change to the template for code blocks.  That _might_ be possible by [overloading the parser](https://github.com/vmg/redcarpet/blob/v3.2.2/README.markdown#and-you-can-even-cook-your-own) used by Jekyll
Option 2: Always manually write the HTML for code blocks.  (I know, right, why did I even include this option!?) 
Option 3: Add a few lines of Javascript to set a `tabindex` property on all code blocks
I chose option 3.
No changes are made to values outside the page.
- Should we go …

BCDA-2326 Accessibility: Keyboard navigation for code sections

---

index.md

According to a `508 Compliance` scan, this homepage has two `h1` tags. The `Overview`  can become `h2`.
- Converted `Overview` section to `h2`.
- Added a link to the `Overview` section on the sidebar.
No PHI/PII is affected by this change.
Before:
After:
Please review.

BCDA-2854: Accessibility enhancement - only one h1 per page

---

_layouts/home.html

According to a `508 Compliance` scan, this homepage has an unnecessary `aria-labelledby` attribute.
- Removed unnecessary attribute.
No PHI/PII is affected by this change.
Site renders locally with no visible regression.
Please review.

BCDA-2852: Accessibility enhancement - remove unnecessary `aria-labelledby`

---

_includes/header.html
_layouts/home.html

- Move page h1 and main navigation into header element. Puts this content inside a landmark to avoid an Axe error.
- Changes the section element to a main one, putting that landmark on the same level as the header and footer elements. Also, adds the `id="main"` so the skip link works. Removes the `role="main"` from the article element; not needed now. And also removes the `id="main"` from the article element.
- Remove the `role="complementary"` from the container div on page navigation. This fixes an Axe error related to nesting landmarks, in this case, having an complementary one inside a main one.
None.
No new Axe errors are present now:
I tested all the pages to make sure moving some of the elements into the header didn't cause any issues, but it would be good to double check. …

BCDA-2855: Improves HTML markup to fix Axe landmark errors

---

_includes/header.html
_layouts/default.html
assets/js/mobile-nav-trigger-button.js

The button that toggles the mobile menu for users can be improved for screen reader users. Adding an additional aria attribute will help them understand that its functionality.
- Added `type="button"` to the mobile menu button
- Added `aria-expanded="false"` to the mobile menu button
- Removed the `href` from the mobile menu button
- Added a script to toggle `aria-expanded` on the mobile menu button
No PHI/PII is affected by this change.
Tested locally using a mobile viewport emulator.
Inactive:
Active:
Please review.

BCDA-2853: Use `aria-expanded` on the mobile menu button

---

assets/js/accordion.js
sandbox/technical_user_guide.md
sandbox/user_guide.md

The button that toggles the accordions for users can be improved for screen reader users. Adding an additional aria attribute will help them understand that its functionality.
- Added `type="button"` to the accordion button
- Added `aria-expanded="false"` to the accordion button
- Added a script to toggle `aria-expanded` on the accordion button
No PHI/PII is affected by this change.
Tested locally.
Inactive:
Active:
Please review.

BCDA-2857: Use `aria-expanded` on the accordion button

---

assets/css/static-main.css

Updates focus colors in a few spots to meet contrast requirements.
- Remove text decoration underline on hover on "Join" link to make it consistent with site title link.
- Remove `.topmenu:focus` CSS to make those links receive proper color on focus.
- Remove `color: #339392` on `.accordion_active` so it meets contrast requirements when accordions are expanded.
- Add `.ds-c-desktop-nav .desktop-nav-items a:focus, .mobile-nav-items a:focus` to focus rules so they go the proper color.
- Change main focus color from white to `#212121` so it meets contrast requirements.
None.
Colors now pass contrast. See screenshots:
Feel free to test it out by tabbing through the pages, double checking to see if the style changes interfered with anything else.

BCDA 2856: Update colors on focus to meet accessibility requirements

---

.travis.yml
scripts/build_and_test.sh

This branch adds continuous integration with travis to the static site.
* Adding `.travis.yml` travis configuration
* Adding `scripts/build_and_test.sh` script
The Travis CI configuration specifies that we're using ubuntu 18.04 (bionic) and the docker service.
To test the site, it runs jekyll serve and greps the response from a request for the home page.
Note that the test steps in `build_and_test.sh` are not dependent on the build step. We can use the build step as a stub for deploying the static site assets.
To test this Travis config, I forked the repo to my personal GitHub and enabled Travis CI. Travis will need to be enabled for `https://github.com/CMSgov/bcda-static-site/` on [this page](https://travis-ci.org/organizations/CMSgov/repositories) before this ticket can be considered …

Adding Travis CI

---

Dockerfiles/Dockerfile.static_site

The `jekyll/builder` image was [updated yesterday on Dockerhub](https://hub.docker.com/r/jekyll/builder/tags).  This new image is not compatible with our processes, causing the following error:
```
Bundler::PermissionError: There was an error while trying to write to
`/usr/gem/cache`. It is likely that you need to grant write permissions for that
path.
An error occurred while installing public_suffix (3.0.3), and Bundler cannot
continue.
Make sure that `gem install public_suffix -v '3.0.3' --source
'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
minima was resolved to 2.5.0, which depends on
jekyll-feed was resolved to 0.11.0, which depends on
jekyll was resolved to 3.8.5, which depends on
addressable was resolved to 2.6.0, which depends on
public_suffix
ERROR: Service …
```

Pin `jekyll/builder` image to version 3.8

---

production/technical_userguide.md
sandbox/technical_user_guide.md

Adds alternate cURL command to our Basic auth technical guides (both sandbox and production guides).  The additional cURL command performs base64 encoding with just the clientId and secret; the sole previous cURL command performs base64 encoding by way of concatenating a header. 
* Introduced heading and content parity between the technical sandbox and production guides
* Added the alternate cURL command
* Removed an imprecise `copy-to-clipboard` snippet in the technical sandbox guide
Tested locally.  Flow across technical sandbox and production guides is as follows:
* Authentication and Authorization
* Basic Authentication Walkthrough
* Request
* Headers
* cURL commands
* Option 1
* Option 2
* Response
* Confirm parity between the technical sandbox and technical production guides
* …

BCDA-2933: Add alternate cURL command to Basic auth technical guides

---

production/technical_userguide.md
sandbox/technical_user_guide.md

There are a few `curl`-related typos in our technical user guide.
- Don't reference the `sandbox` URL on the production user guide.
- No need to specify the `Basic Authorization` header when using the `--user` flag with `curl`
- Need to make sure the `accept: application/json` header is supplied in the examples
Reviewed locally.
Please review.

Fix Typo in Technical User Guide

---

production/technical_userguide.md
production/user_guide.md
sandbox/technical_user_guide.md
sandbox/user_guide.md

`since` parameter validation has been refined/restricted to only allow FHIR `instant` datatype, as per the Bulk FHIR Specification.  Our documentation should reflect this as well.
`since` parameter documentation has been updated to indicate FHIR `instant` datatype, as per the Bulk FHIR Specification.
Local rendering is accurate.
Please review.

Update docs to indicate that _since parameter must be in FHIR instant format

---

production/technical_userguide.md
production/user_guide.md
sandbox/technical_user_guide.md
sandbox/user_guide.md

Fixes typos, updates anchor links, and standardizes image locations and formatting in sections discussing the _since parameter.
* Add anchor links to previous sections of the user guides when those sections are referenced in the _since instructions
* Production user guides: minor edits for clarity on requesting historical data before using _since parameter
* Swagger walkthroughs: add alt-text to Swagger images referencing cURL commands
None
* Confirm language changes made language better, not worse
* Confirm anchor links work

Formatting updates for _since in user guides

---

index.md

The AB2D project went live with their website today, so we should include a reference to it on our static site.
- Added AB2D information to `FHIR APIs at CMS` section
Pushed feature branch to `stage` and validated the content.
Please review.  Do we want AB2D to be first in the list, due to alphabetic order?

Add AB2D Information to BCDA Static Site

---

Dockerfiles/Dockerfile.static_site
_includes/head.html
_version_config.yml

Adding the release number or branch name to the static site so developers can quickly determine which version of the page they are currently looking at. Related to https://github.com/CMSgov/bcda-ops/pull/508
* added a new `meta` tag to the site header that pulls its content from the site configuration
* added a new file called "_version_config.yml" that will have the site's version configuration
* included the new config file in the build command for jekyll
Deployed to staging environment with jekyll
Should the default for version be "latest" if for some reason the version is not updated when it is deployed?

BCDA-3368 Added Site Version to Static Site

---

production/technical_userguide.md
sandbox/technical_user_guide.md

Instead of listing the entire OpenAPI-related links, lets embed the links into the text (consistent with other areas of text on the site).
- Fixed links in OpenAPI section
Before:
After:
Please review.

Update OpenAPI links

---

production/technical_userguide.md
sandbox/technical_user_guide.md

A google group question revealed an error in how we presented the syntax for making a filtered request using _since.
Replace incorrect `?_since` syntax when _since is the second query being added with the correct `&_since` syntax.
Code has been corrected in all eight locations where the wrong code had been populated.
None
Please make sure I didn't break anything I shouldn't have or overcorrect things that were already accurate.

Efrankle/bcda-3754 - fix _since syntax in technical guides

---

_includes/guide/fhir_types.html
_includes/guide/try_the_api.html
guide.html

Styling/Content changes related to Getting Started page.
1. Remove "current" label on vertical nav bar entries. We had this property set which made them all appear to be "current".
Before: 
After:
2. Update formatting on cURL statements (new line, line continuation, etc.)
1. Approval from H-Team

BCDA-3922 - Content changes to Getting Started page

---

_includes/guide/try_the_api.html

Fixing language on the Try the API page by getting rid of filler language.
- Changed four list items in the Try the API section
- [X ] no PHI/PII is affected by this change

Remove filler language on Try the API

---

index.html

Removed the "Reduce Burden" section from the "How can ACOs benefit from BCDA" section.
It now shows the other three items.
Remove Burden removed from static site.
Please verify that this is the only content that needs to be updated.

Remove "Reduce Burden" section from value prop

---

_includes/head.html
_layouts/default.html

1. Remove Google Analytics script from the HEAD section. This conflicted (and caused issues) with the correct setting in the BODY section.
2. Adding script to add utag.link events when user clicks any of the side nav elements.
1. Validated with the BLAST team that removing the GA script from the HEAD section fixed the issue of reporting events.
2. Using Omnibug extension, validated that we have a GA event when clicking on the side nav elements.

BLSTANALYT-1933 - Fixing issues around reporting google analytics events

---

index.html

We had contrast issues with links found within our Updates section. See:
Apply [CMS Design inverse text color scheme](https://design.cms.gov/styles/base/). We are also using this scheme in our FAQ section (which also has a dark background).
Added some dummy links to verify the contrast is working as expected.

Fix contrast issue with the homepage's update section

---

_includes/build/access_token.html
_includes/build/authorization.html
_includes/build/bcda_credentials.html
_includes/build/requesting_data_EOY.html
_includes/build/requesting_data_all_three.html
_includes/build/requesting_filtered_data.html
_includes/build/requesting_filtered_data_since_Group.html
_includes/data/cclf_v_bcda.html
_includes/data/data_dictionary.html
_includes/data/sample_files.html
_includes/footer.html
_includes/guide/bcda_environments.html
_includes/guide/bcda_parameters.html
_includes/guide/bcda_resource_types.html
_includes/guide/group_endpoint.html
_includes/guide/production_environment.html
_includes/guide/try_the_api.html
_includes/updates/intro.html
_sass/components/_guide.scss
_updates/2020-10-28.html
_updates/2020-12-22.html
_updates/2020-12-29.html
build.html
guide.html
index.html

Following our final round of language and formatting reviews, this PR represents the final updates to the glown-up static site.
* Add padding between bottom of content and footer
* Even out the vertical location of homepage buttons
* Update relative links to ensure they go to the new site, not the old site
* Very small typo and grammar fixes
- [ X ] no PHI/PII is affected by this change
Please confirm using stage that:
* links go where they're supposed to go
* nothing that wasn't broken earlier is newly broken
* there are no remaining instances of "the BCDA" (should be "BCDA"), "Note:", or "12/31/30" as a serviceDate.
Give yourself a big pat on the back and high-five a teammate remotely.

Final updates to static site

---

_includes/build/bcda_user_guide.html
_includes/build/requesting_data.html
_includes/build/requesting_data_EOY.html
_includes/build/requesting_data_EOY_intro.html
_includes/guide/group_endpoint.html

Resolving remaining AXE issues before static-site-glowup release
1. Fixing duplicate IDs. We had duplicated the checkJob and downloadData IDs when we introduced the EOY section.
2. Fixed a couple of auth links that linked outside of the site (instead of referencing internal links)
3. Ensured that H tags are in descending order.
1. Ran AXE tests locally and verified that all errors are resolved.
```
docker run --init --rm --cap-add=SYS_ADMIN orenfromberg/axe-puppeteer-ci:1.0.0@sha256:e7fd3be771e95588296c67dbc73deaa845fc01f385494d56269739d7eb906188  http://host.docker.internal:4000
0 violations found!
docker run --init --rm --cap-add=SYS_ADMIN orenfromberg/axe-puppeteer-ci:1.0.0@sha256:e7fd3be771e95588296c67dbc73deaa845fc01f385494d56269739d7eb906188  http://host.docker.internal:4000/guide
0 …
```

Fixing remaining AXE errors

---

Dockerfiles/Dockerfile.static_site
Gemfile.lock
README.md

The development team for `jekyll/builder` pushed out an [update](https://hub.docker.com/r/jekyll/builder/tags?page=1&ordering=last_updated) before the holidays, resulting in some dependencies to be upgraded.  We should pull those dependency updates into our `Gemfile.lock`
- Update `Gemfile.lock` to reference `bundler v2.2.2`
Completed a successful [build/deploy](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Deploy%20-%20Static%20Site/111/parameters/) to stage from this feature branch.
Please review.

Update to bundler version 2.2.2

---

_includes/guide/credentials.html

Updating synthetic ACO credentials on sandbox to reflect newly generated client secrets.
Static site updated to reference new set of client secrets for our various test ACOs.
Affect synthetic ACOs, so no real PHI/PII information involved.
1. Validate that all of the clientID:clientSecret tuples work as expected.
1. Once this PR is merged and deployed to production, we need to remove the other set of credentials.

BCDA-4231 - Update credentials to newly refreshed ones

---

_includes/guide/since_parameter.html
_includes/guide/type_parameter.html

There have been some long running typos on the guide section of the site for descrying the `type` and `since` parameters.
- Update `since_parameter.html` with the appropriate description.
- Update `type_parameter.html` with the appropriate description.
The `_type` and `_since` parameter sections on the guide give their proper descriptions.
Let me know if I should add or edit any other wording.

bcda-4547 Feature: Update static site typos

---

scripts/build_and_test.sh

The static site is scanned for accessibility issues on a weekly basis; but there is a desire to shift left, run accessibility scans early/often, and block PRs when there is an accessibility regression.
- Added accessibility scanning within GitHub Actions.
Successful execution in Github Actions within this feature branch.
Please review.

Run Accessibility Scan in Github Actions CI

---

_config.yml
quickstart.html

The `quickstart.html` file is deprecated, and no longer used within the Static Site.  However, it is still being built and renders an incomplete page if directly accessed.
- Removed `quickstart.html`
- Removed "DEMO" verbiage in config file
We are now seeing `404` when accessing `quickstart.html`.
Please review.

Remove deprecated Quickstart file

---

ops/Jenkinsfile.build_trigger

BCDA currently uses SSH Keys to integrate with Github from Jenkins, which relies on the SSH key to be stored on the Jenkins volume.  To simplify the migration to the new contract, the strategy will be updated to use Personal Access Tokens to integrate with Github (which is identical to the strategy being used on the DPC project).  
This should be considered an enhancement, as the tokens will be stored in Jenkins Credential Management System as opposed to a nebulous location on the Jenkins volume.
We should migrate to use Personal Access Tokens to integrate with Github from Jenkins.
- Added a new Personal Access Token to the BCDA Jenkins Credential Management System
- Updated the Checkout Strategies for all relevant Jenkins jobs to ensure that it is using the new credential
> Access is …

BCDA-3047: Use Github PAT over HTTPS instead of SSH Key

---

_includes/build/access_token.html
_includes/build/bcda_v2.html
_includes/guide/bcda_v2.html

https://jira.cms.gov/browse/BCDA-7198
- Update URL in instructions to point to `/auth/token`
- Update bearer string in instructions to match the client ID/secret in Option 2
Noticed that these instructions are a little inaccurate and don't actually work. They should be updated so folks can successfully retrieve short-lived tokens in sandbox.
Validated by running the new cURL command locally.

BCDA-7198: Fix curl instructions for retrieving sandbox tokens

---

_includes/guide/try_the_api.html

Remove whitespace from sandbox token cURL command. Copy/Paste of this command failed due to the newline character
~https://jira.cms.gov/browse/BCDA-xxx~
Remove whitespace from sandbox token cURL command. Copy/Paste this command was broken due to the newline
@laurenkrugen-navapbc caught this broken command when walking through the documentation. The same command is used in [the build instructions](https://github.com/CMSgov/bcda-static-site/blob/deac7639b912dc016e30171a34d990a637be1ff7/_includes/build/access_token.html#L46-L48)
@laurenkrugen-navapbc has validated this cURL command during connectathon prep work

Fix cURL command to get a sandbox token in try_the_api.html

---

_includes/partial/faq.html
scripts/build_and_test.sh

https://jira.cms.gov/browse/BCDA-7333
- Add partial.html to list of pages for a11y scanning
- Replace h4 tags with bolded div text
- A new page was added, but it is not being accessibility-scanned.
- The h4 tags violate the heading level checks from axe which state that headings should only increase by one. The h4 tags in the FAQ were following the h1 tag for the section title. Instead, replace them with bolded divs. Note that the h4 tag does not actually apply any font-size styling, so we don't need to use the `ds-u-font-size--h4` class.
- PR checks should pass.
- Verified FAQ output looks the same:
|Before|After|
|---|---|
|<img width="803" alt="Screen Shot 2023-08-22 at 12 28 47 PM" src="https://github.com/CMSgov/bcda-static-site/assets/2308368/f9d26e7c-b90d-44d4-822d-0e58e3ee47df">|<im …

BCDA-7333: Run a11y scans on PACA page

---

_includes/footer.html

~https://jira.cms.gov/browse/BCDA-xxx~
Fixed a broken link in the footer to the plain writing guide.
Clicking the "Plain Writing" link in the footer, brings the user to a 404 page
The updated link directs to 

Fix footer link for Plain Writing

---

_includes/build/attribution_status.html
_includes/build/bcda_v2.html
_includes/build/cancelling_jobs.html
_includes/build/jobs_history.html
_includes/build/request_metadata.html
_includes/build/requesting_data_all_three.html
_includes/build/requesting_data_runouts.html
_includes/build/requesting_filtered_data_since_Group.html
_includes/build/requesting_filtered_data_since_Patient.html
_includes/guide/bcda_v2.html
_includes/guide/try_the_api.html

https://jira.cms.gov/browse/BCDA-7331
- update cURL commands to use BCDA V2 and `/Group/all` in our general guidance
- minor updates to content supporting the sample cURL commands
- improved formatting for a few cURL commands
- other small corrections unrelated to cURL commands
Some changes to align with recommended use of the API. Encourage use of BCDA V2 over V1 and the /Group endpoint over the /Patient endpoint. There are some other very minor changes to content to align with the updated code samples, but a more comprehensive review of the guidance is planned in [BCDA-7330](https://jira.cms.gov/browse/BCDA-7330)
Executed the new sandbox curl commands locally and inspected static site visually on stage.bcda.cms.gov
If any security implications apply, add Jason Ashbaugh (GitHub username: …

BCDA-7331: Update cURL commands to use V2 and other recommended options

---

_includes/data/additional_resources.html

https://jira.cms.gov/browse/BCDA-7460
Reverted the "Additional Resources" section to use an ordered list.
- https://github.com/CMSgov/bcda-static-site/pull/186 contains the changes of the ndjson links.
ran locally.

BCDA-7460: reverting additional resources to ordered list

---

_includes/build/requesting_data_all_three.html

https://jira.cms.gov/browse/BCDA-7818
- update to the text under `Files expire after 24 hours.`, per the ticket description.
Clearer language.
Ran locally and verified output. Also verified in [stage](https://stage.bcda.cms.gov/build.html).
**Current Text:** 
**New Text (PR changes):**

BCDA-7818: Update documentation for 24 hour job archive rule

---

_data/credentials.yml
_includes/guide/adv_credentials.html
_includes/guide/bcda_enhancement_credentials.html
_includes/guide/credentials.html
_includes/guide/try_the_api.html

Add "dynamic" loading for Try The API code snippets. Puts test credentials into YML file which can be used for the rest of the codebase or other credentials.
https://jira.cms.gov/browse/BCDA-7973
(What was added, updated, or removed in this PR.)
Added YML file to hold sandbox clients and secrets.
Updated existing usages of hard-coded clients and secrets to pull from YML file.
N/A
Viewed changes within local environment.

BCDA-7973: Add loading for Try The API creds

---

_includes/updates/links.html

Removes misleading Google Group announcement.
https://jira.cms.gov/browse/BCDA-7992
Removed HTML block with the announcement.
N/A

BCDA-7992: Remove announcement of Google Group

---

_includes/build/bcda_v2.html
_includes/build/requesting_data_all_three.html
_includes/build/requesting_data_runouts.html
_includes/build/requesting_filtered_data_since_Group.html
_includes/build/requesting_filtered_data_since_Patient.html
_includes/guide/bcda_v2.html
_includes/guide/try_the_api.html
_includes/partial/faq.html

https://jira.cms.gov/browse/BCDA-8113
Ensure "Try the API" credentials show properly
Escape export operator to ensure that all environments can utilize the CURL commands. 
When we fixed the curl commands for windows cmd, we broke it for powershell. Now, everyone can live in harmony. 

BCDA-8113: Escape export operator and fix credential rendering

---

_includes/build/best_practices_download_speed.html
_includes/build/requesting_data_all_three.html
build.html

https://jira.cms.gov/browse/BCDA-8124
1. Add best practices for speeding up downloads
2. Link to speeding up downloads from guide
Content drafted in BCDA-8000 and published to https://stage.bcda.cms.gov/build.html
Deployed to staging and verified links work
https://stage.bcda.cms.gov/build.html#speeding-up-downloads
https://stage.bcda.cms.gov/build.html#requesting-all-three

BCDA-8124: Best practices for speeding up downloads

---

_data/credentials.yml

https://jira.cms.gov/browse/BCDA-8196
Rotated sandbox credentials and ensured Advanced Large entity is pointed to the correct value.
Existing Advanced-Large entity points towards a non-existent model entity, this rotates the credentials for the public sandbox client ids.
Can start export jobs with all of the updated credentials.

BCDA-8196: Rotate public sbx credentials

---

_includes/data/additional_resources.html
common/data_guide.md

https://jira.cms.gov/browse/BCDA-8272
Bulk FHIR IG link has been updated. 
The link to the Bulk FHIR specification points to an old IG that hasn't been updated in a long time and should not be referenced as an approved standard.
Go to [Additional Resources ](https://bcda.cms.gov/data.html#additional-resources)(2nd item in the list) - link takes the user to https://build.fhir.org/ig/HL7/VhDir/bulk-data.html 
Expected: link should take the user to https://hl7.org/fhir/uv/bulkdata/
Ran locally and verified link works correctly.

BCDA-8272: Update link to the Bulk FHIR specification on the website

---

_includes/guide/bcda_enhancement_credentials.html

https://jira.cms.gov/browse/BCDA-8288
Small REACH ACO - 100 → 110
Large REACH ACO - 10,000 → 11,000
Website needs to accurately reflect the number of enrollees in the synthetic data sets after the changes in [BCDA-8125](https://jira.cms.gov/browse/BCDA-8125).

Update partially adjudicated claims data sets - enrollee count

---

_includes/build/access_token.html

Address feedback from Karley's review of staging r79
https://cmsgov.slack.com/archives/CHG7Q7XNH/p1730998587225749
Remove option 1 to request a token using curl
we don't provide a sample command on how to actually encode the credentials, and it's cleaner to just point everyone to the curl command with the --user flag
Validated in staging

Remove option 1 to request a token using curl

---

_includes/build/bcda_credentials.html
_updates/2024-11-18.html
build.html

https://jira.cms.gov/browse/bcda-8434
Added the updated credential management instructions to build.html and included a small announcement in updates.html
This content was originally drafted to be a new subpage in a redesigned version of the site, but can be dropped into the current site. It will be helpful for new model entities joining in 2025 and getting started with BCDA.
1. Published to staging site for review by @phamjennifer
2. Validated links from side navigation and from updates.html work as intended to /build.html#bcda-credentials

BCDA-8434 Update credential management guidelines

---

_includes/build/best_practices_download_speed.html
_includes/build/requesting_data_all_three.html
_includes/guide/try_the_api.html

https://jira.cms.gov/browse/BCDA-8390
Adjusting the file download curl command to specifically download a file as output instead of return bits from the request as well as adjust the copy to acknowledge that the file downloaded is a gzip and will need to be extracted to be used.
Site build and review locally.

BCDA-8390-adjust-file-download-copy

---

build.html

https://jira.cms.gov/browse/BCDA-8392
Added runout data description.
Site build and review locally.

BCDA-8392-add-runout-description

---

.github/workflows/508_compliance_check.yml
.github/workflows/deploy.yml
.github/workflows/tag_and_deploy.yml

https://jira.cms.gov/browse/BCDA-8636 and https://jira.cms.gov/browse/BCDA-8639
Added tag, deploy, and 508 compliance GHA workflows.
Moving off of jenkins: https://jira.cms.gov/browse/BCDA-8624
I verified these workflows by hardcoding the various inputs to staging and running them `on: push`.

BCDA 8636: Add workflows for tag, deploy, release, and 508 compliance

---

.github/workflows/508_compliance_check.yml

https://jira.cms.gov/browse/BCDA-8639
Added env var that can be set when a workflow is run from a cron expression.
Previously the input workflow env var was not accessible during a cron execution.  See failure here: https://github.com/CMSgov/bcda-static-site/actions/runs/12743251972

BCDA-8639: Fix cron issue in workflow

---

.github/workflows/508_compliance_check.yml

[BCDA-8664](https://jira.cms.gov/browse/BCDA-8664)
Added slack alerts for when the Workflow fails or succeeds. 
The previous Jenkins job had alerts going to the Slack channel of bcda-alerts.

508 Compliance Slack Alerting

---

.github/workflows/deploy.yml

n/a
Updates deploy step so dev S3 bucket doesn't delete directories used by the `uswds-redesign` preview URLs
Deleting all the contents of dev S3 breaks the redesign preview links by removing the directories that contain the files for those links
Manual QA

Update deploy workflow so dev bucket doesnt get deleted

---

_data/credentials.yml
_includes/build/access_token.html

https://jira.cms.gov/browse/BCDA-9016
Updated the newly-rotated test credentials for the "Try the API" guide on the static site.
The credentials for the sandbox "try me" demo were rotated before their June expiration. Note that these are exposed secrets in the repo and are intended for the public on the static site.

BCDA-9016: Update rotated test credentials

---

.github/workflows/tag_and_deploy.yml

https://jira.cms.gov/browse/BCDA-9141
Add runner to tag workflow call out.  Correct stage env in deploy workflow call out.
Full tag and release workflow has not been fully run since GF migration so there were a few kinks to work out.
Successful run from PR branch: https://github.com/CMSgov/bcda-static-site/actions/runs/16351475206/job/46199171923

BCDA-9141: Adjust tag and deploy workflow

---

.github/workflows/deploy.yml
.github/workflows/promote.yml
.github/workflows/push-dev.yml
.github/workflows/release.yml

https://jira.cms.gov/browse/BCDA-9309
Update github actions to account for renaming uswds-redesign to main
The working redesign branch uswds-redesign has been renamed to main, main was renamed to legacy to preserve the git history.
This update updates the GH Action scripts to now use main instead of uswds-redesign

BCDA-9309 Update workflows to reflect branch renaming

---

.github/workflows/a11y-check.yml
.github/workflows/broken-link-check.yml
.github/workflows/comment-pr.yml
.github/workflows/deploy.yml
.github/workflows/promote.yml
.github/workflows/pull-request.yml
.github/workflows/push-dev.yml
.github/workflows/release.yml

- updated the deploy workflow (and other workflows) to associate PR deployments with a subpath under `/feature/{PR#}`
- updated the deploy workflow (and other workflows) to associate deployments from main with the staging root path `/`
Presently, when changes are merged to main, they are deployed to the url https://stage.bcda.cms.gov/main/. This paradigm adds some difficulty to the prod promotion process:
1. the base url of the main deployment in staging (`/main`) is different from that of prod (`/`), which means that for every promotion, and temporary change must be introduced tot he staging workflow to remove the base url
2. the exact build promoted to prod is _not_ identical to the build tested in staging, since the staging build must be reproduced in the above point, and that build …

Update deployment paths in workflows
