_layouts/default.html, assets/css/static-main.css, assets/js/accordion.js, sandbox/user_guide.md
Fixes [BCDA-2339](https://jira.cms.gov/browse/BCDA-2339)
Problem:
Before this change there was no way for our users to test different sized payloads in our synthetic environment. This change gives them a chance to emulate a more realistic scenario by more closely matching the size of the data they'll see in production.
Proposed Changes:
Added 4 different sized synthetic credentials for use in our sandbox environment.
Change Details:
_layouts/default.html - added script path to the accordion javascript.
assets/css/static-main.css - styling for the accordion.
assets/js/accordion.js - javascript for the accordion
sandbox/user_guide.md - added different sized ACO's for synthetic use.
Security Implications:
This change does **not** deal with any PII/PHI. The credentials added are completely …
=> BCDA-2339 Feature: Updating user guide to reflect varying sized creds for sandbox usage

production/technical_userguide.md, sandbox/technical_user_guide.md
Fixes [BCDA-2387](https://jira.cms.gov/browse/BCDA-2387)
Problem: It's been a concern from our API users that a test client would be helpful for knowing how to interact with our API programmatically. This pr includes a link to our test client that demonstrates all of the steps for API interactions. Requesting a token, making a request, polling for job status, and receiving a fhir payload.
Proposed Changes:
Added an example code link to our test client on the user guide.
Change Details:
production/technical_userguide.md - Added language and a link to our smoke test client (bcda_client.go)
sandbox/technical_user_guide.md - Added language and a link to our smoke test client (bcda_client.go)
Security Implications
No, this change does **not** deal with any PII/PHI data. This is only an update …
=> BCDA-2387 Feature: Added test client to user guide

common/data_guide.md
To avoid confusion for screen readers, do not skip levels for headings.
- Change two instances of h4 to h2
The change has a slight visual affect, but no change to the data in this documentation.
All credit to Terrance Bell!  All feedback welcome!
=> BCDA-2323 Accessibility: Ensure headings do not skip levels

production/technical_userguide.md, sandbox/technical_user_guide.md
Screen readers have a difficult time when headings jump levels.  This ticket asks for changes in the production user guide; other tickets address other pages.
- Change specific instances mentioned in ticket (separate tickets cover other pages)
- Tweak format for `Request` heading lower in the page to be consistent
- Duplicate `Request` heading changes in the `sandbox` user guide
No data or instructions have been changed.
Are there any concerns over this change?
=> BCDA-2321 Accessibility: Ensure headings do not skip levels (part 2)

README.md
- Added Docker to the "Requirements" list
- Added the definition of a Gem file in "Installation"
- Added the importance of using Docker to build, instead of building locally, in "Using Docker for distributed builds"
Only changes are verbiage-related.
Additions called out with orange underlines:
Do you prefer different wording?
=> BCDA-2770: Update README to include Docker install instructions

_includes/copy_snippet.md, _includes/header.html, assets/css/static-main.css
The CMS Design System elements until recently had subtle, color-only indications of focus.  The goal of this PR is to take advantage of recent updates to the design system that make focus more obvious.
- Isolate any CSS changes BCDA had made outside of the commented BCDA-specific section
- Original CSS lines 54-55, 79-80, 7344
- Update CMS Design System Core CSS
- Original CSS lines 243-4997
Note that the CMS Design System Layout has not been altered (lines 4997-6041).
This is a format-only change.
- Please run this locally, as there is a potential impact on unexpected design elements.  Does all look OK?
- Based on the screenshots/local experience, do we need to make any custom changes to visible focus state?  In particular, is the color (new! custom!) for selected links appropriate, or …
=> BCDA-2302 Accessibility: Visible focus state

common/data_guide.md, index.md
Replacing Blue Button verbiage with BFD
Just replaced any relevant mentions of BB with BFD language instead. 
Simple find and replace, N/A
N/A
Just check to make sure that the language for BFD makes sense.
=> Replace BB verbiage with BFD verbiage.

.github/pull_request_template.md
Add checkbox to PR template to address any PHI/PII changes.
Any other details to include in the PR template?
=> BCDA 2977 : Tweak security section OR template to address PHI/PII changes

production/user_guide.md, sandbox/user_guide.md
Added .ndjson text for users to include the whole file type (including NDJSON), but this was not stated in the user guide. This instruction was shown in the correlating image, but not mentioned in text.
* Added .ndjson text for clarification when adding bene data in sandbox (beginner UG)
* Added .ndjson text for clarification when adding bene data in prod (beginner UG)
* Made sure that all mentions of PNG are now SVG
* Made sure the .ndjson text clarification is within the curly braces.
Yes, validated.
Please make sure I didn't break the site, thank you!
=> Added NDJSON to text, to clarify Swagger instructions.

ops/Jenkinsfile.build_trigger
Need to implement CI/CD for this new staging site to mimic the live site, so that we are able to catch and remediate any errors before broadcasting.
Introduce a Jenkinsfile build trigger to scan a successful merge to master to run a deployment job to staging environment
=> BCDA 3266 Feature: Introduce CI/CD

production/technical_userguide.md, sandbox/technical_user_guide.md
Adding in a new section in the technical user guide to show how to use the OpenAPI json we provide to generate a client for interacting with BCDA.
* Added a new "Generate Client Code" section to the technical user guide with instructions on how to generate client and some warnings on some common issues to smooth adoption
Are the instructions clear and concise and match the language for the rest of the user guide?
=> BCDA-3539 OpenAPI code generation guide

_config.yml, data.html, guide.html, quickstart.html, terms.html, updates.html
Updated the global navigation for the header with the new pages for the static site glowup
* Updated the jekyll configuration "global_nav" to include the new pages
* Added metadata tags to new pages
Start locally and navigate to `localhost:4000` to see new header navigation links. Those links should all point to the correct pages
=> BCDA-3771 updated navigation and added page metadata

index.md, production/technical_userguide.md, production/user_guide.md
We no longer do manual onboarding, we need to update language to reflect that.
Four instances of language changes
1. Home Page 1
2. Home Page 2
3. PROD Basic
4. PROD Technical
Reference the Confluence for more
Changed all mentions of the Production Queue from the site to direct folks to the ACO-MS portal account instead. Referencing this Confluence: https://confluence.cms.gov/pages/viewpage.action?spaceKey=BCDA&title=ACO-MS+Automated+Onboarding+User+Guide+Changes
- [ X] no PHI/PII is affected by this change
Please check if there are ANY other areas in the site that need to be changed because of our switch to ACO-MS.
=> Update Site language to include ACO-MS Portal and not PROD Queue

_includes/terms/terms_of_service.html, terms.html
Created the new terms of service page
* Created the content files for the terms of service
* Added styling and content to the terms of service page
=> BCDA 3799 Terms of Service page

_includes/updates/2020-10-27.html, _includes/updates/2020-10-28.html, _includes/updates/_README.md, _includes/updates/_example_update.html, _includes/updates/intro.html, updates.html
Added the new update page sections with guide on how to create future updates
=> BCDA-3798 Updates page

_includes/data/cclf_v_bcda.html, _includes/data/data_dictionary.html, _includes/data/sample_files.html, _includes/data/security_and_quality.html, data.html
Added the files and formatting for data page
=> BCDA-3797 Data page

index.html
1. Fix typo in  homepage
2. Updates to FAQ section
1. Verify content was updated correctly.
=> Fix various homepage entries

_includes/build/requesting_filtered_data.html, _includes/data/data_dictionary.html, _includes/data/security_and_quality.html, _includes/footer.html, _includes/guide/try_the_api.html, _layouts/default.html, _sass/base/_base.scss, build.html, data.html, guide.html, index.html, terms.html, updates.html
When running our [508 compliance scan](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Static%20Site%20508%20Compliance/), we uncovered various issues related to accessability.
1. Fix issues related to page-content not being captured in landmarks
2. Fix skip-links to anchor to actual main tag.
3. Fix various heading issues (going from h1 --> h3 directly).
Ran the axe scan on all of our pages and verified that no violations were reported.
```
docker run --init --rm --cap-add=SYS_ADMIN orenfromberg/axe-puppeteer-ci:1.0.0@sha256:e7fd3be771e95588296c67dbc73deaa845fc01f385494d56269739d7eb906188  http://host.docker.internal:4000
0 violations found!
docker run --init --rm --cap-add=SYS_ADMIN orenfromberg/axe-puppeteer-ci:1.0.0@sha256:e7fd3be771e95588296c67dbc73deaa845fc01f385494d56269739d7eb906188 …
```
=> Fixes various reported by axe testing

_includes/guide/try_the_api.html
Fixing typos in the cURL commands with the use of quotes
The use of quotes was not consistent in the commands of the Try the API section. This was causing errors after copying and pasting.
Replace double quotes with singles in Step 2 and 3, add single quotes to Step 4
- [X ] no PHI/PII is affected by this change
Yes, all quotes are appearing as double quotes now.
=> BCDA-4009: Correct typos in the Getting Started page commands

_config.yml
The code which defines the list of files to exclude from `_site` needs to be updated.
Add files to be excluded under `_config`
-  package.json
- package-lock.json
- ops/
- scripts/
- Makefile
=> [BCDA-4324] Fix: Update list of files to exclude under _config

_updates/2021-02-09.html, _updates/2021-02-16.html
BCDA had two large announcements to make: reaching data parity with CCLF and implementing the DELETE endpoint. This is the basic start to updating the static site to reflect these changes. 
- Add a data parity Update with a link to the GG Announcement
- Add a DELETE endpoint Update with a link to the Building Your Application page
For the DELETE endpoint, more changes need to be made to add detail on the Building Your Application page and the Try the API page.
- [ X] no PHI/PII is affected by this change
Yes, Updates are appearing as expected on my local machine.
=> BCDA-4292 Data Parity and Delete Endpoint: Added two updates to the Updates page

_includes/guide/endpoint_alert.html, _includes/guide/since_parameter.html, _includes/guide/type_parameter.html, _includes/guide/what_is_an_api.html, _updates/2021-01-25.html, _updates/2021-02-09.html, _updates/2021-02-16.html, _updates/2021-06-01.html
Various small fixes and an update to the updates page.
- Add Update for the data dictionary changes
- Fix broken link(s)
- Fix links that are hard coded to the production static site.
- Fix links that are opening new tabs when they should be redirecting within the same tab on the same page to a different section.
- Fix incorrect dates in the updates page.
Various fixes and update addition are reflected properly on the static site.
Let me know if I missed anything.
=> bcda-4613 Feature: static site changes

_includes/data/bcda_v2_data.html, _includes/guide/try_the_api.html, _updates/2021-07-14.html, build.html, data.html, guide.html
These changes were requested following a review of the site.
- "Understanding Your Data" - Copy update "V2 Data Dictionary" -> "BCDA Data Dictionary" and drop link
- Banner notice copy update - Add a space "BCDA Version 2(V2)"
- Try the API - all URLs should reference `sandbox`
- Homepage and Updates page - copy edit requested by Jimmy, Approved by Nicole.
See above
These are all copy changes. Confirm that all items listed above are present in code. 
Please let me know if I missed anything. Otherwise, a nice 👍 would be great!
=> [BCDA-4732] Requested R39 Updates

_includes/guide/adv_credentials.html, _includes/guide/credentials.html
As we get closer to the year mark, we are in the season of credential rotations. We have rotated the opensbx credentials, and now need to update the static page with new credentials.
We change two files to reflect the update in opensbx credentials. These ARE NOT prod cred.
Ensure the credentials match keybase.
Yes
=> BCDA-5149 - Credential rotations

_includes/data/data_dictionary.html
Corrected the month the data dictionary was last updated to january.
=> Correct updated month for data dictionary

_includes/header.html, _includes/usa_banner.html, assets/css/static-main.scss, ops/release.sh
- Implement USA banner on website
- Verify USA banner is responsive
=> BCDA 5587: Implement USA banner on website

_includes/guide/group_endpoint.html, _includes/guide/patient_endpoint.html
Fix broken hyperlink for /Patient and /Group endpoint links
update the hyperlink address to the correct one
update the hyperlink address to the correct one
=> BCDA-5502: Fixing broken links on static site | 404 Errors

_includes/footer.html
Implement vulnerability footer links
- Add a link to the CMS Privacy Policy beneath the USA.gov link in the Additional Resources link list : https://www.cms.gov/About-CMS/Agency-Information/Aboutwebsite/Privacy-Policy
- Add a link to the CMS Vulnerability Disclosure beneath the CMS Privacy Policy link in the Additional Resources link list https://www.cms.gov/vulnerability-disclosure-policy
- Add a link to the developer.cms.gov at the bottom of the CMS & HHS Websites link list https://developer.cms.gov/
- Add a link to the U.S. Web Design System below the CMS Design System link in the Additional Resources link list https://designsystem.digital.gov/
- remove the link to mymedicare.gov
Testing Instructions:
Confirm the links are on the static site, open in a new tab, and are in the order …
=> BCDA-6364: Implement vulnerability footer links

_includes/build/access_token.html, _includes/guide/try_the_api.html
Manual inspection of extra-small model entity published on static site
=> BCDA-6618 Update sandbox credentials for extra-small entity model

_includes/data/partially_adjudicated.html, _includes/guide/bcda_enhancement_credentials.html, _includes/guide/try_the_api.html, data.html
To add BCDA Partially Adjudicated Enhancement information
- Add BCDA Partially Adjudicated Enhancement credentials to the guide
- Add BCDA Partially Adjudicated Enhancement intro to data page
- Added additional small & large DCE credentials to guide.html
- Added introduction text to data.html
=> PACA-748 - Update BCDA site with Partially Adjudicated Enhancement Sandbox Instructions

_includes/data/partially_adjudicated.html, _includes/guide/bcda_enhancement_credentials.html, _includes/guide/try_the_api.html, data.html
https://jira.cms.gov/browse/BCDA-6825
- Update BCDA Partially Adjudicated Enhancement credentials in the guide 
- Update BCDA Partially Adjudicated Enhancement intro on data page 
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
- Assert that copy on data page matches [this copy ](https://confluence.cms.gov/pages/viewpage.action?pageId=771530852)
- Assert that credentials guide matches [this copy ](https://confluence.cms.gov/pages/viewpage.action?pageId=771530946)
=> bcda-6825 - Update BCDA site with partially adjudicated enhancement sandbox instructions 

_includes/data/partially_adjudicated.html, _includes/guide/bcda_enhancement_credentials.html, _includes/guide/try_the_api.html, data.html
https://jira.cms.gov/browse/BCDA-6838
(What was added, updated, or removed in this PR.)
- partially_adjudicated: replace DCE with REACH ACO
- bcda_enhancement_credentials: replace DCE with REACH ACO 
- try_the_api: replace seven with nine 
- data: remove 'closes gaps in access to claims
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
- Previous changes were reviewed by Karley and these changes were requested 
=> BCDA-6838: Content updates for PACA enhancement

.github/pull_request_template.md
https://jira.cms.gov/browse/BCDA-6997
Adds standard security section to pull request template.
=>   BCDA-6997: PR Templates - Security Section

.github/pull_request_template.md
https://jira.cms.gov/browse/PLT-77
Shortened security implications section in PR template to match standard.
Addendum to #169.
Final wording checked with @bhodges-navapbc.
=> PLT-77 Shorten security implications section

_includes/partial/user_guide.html
https://jira.cms.gov/browse/BCDA-7332
- update PACA user guide 
- new user guide should be linked from user guide page 
https://github.com/CMSgov/bcda-static-site/assets/14364118/ed59c4e7-bec7-4c13-afc6-0e99800b7ab6
- assert that the user can view: https://app.box.com/file/1282441965098?sb=/activity/versions/1401895878698 when attempting to navigate to user guide download link
=> BCDA-7332: update PACA user guide

_includes/guide/adv_credentials.html, _includes/guide/bcda_enhancement_credentials.html, _includes/guide/credentials.html
https://jira.cms.gov/browse/BCDA-7437
- Rotate sandbox credentials to ensure continuity of testing
This rotates our documented shared sandbox credentials so folks can continue to use our sandbox environment :)
Verified each credential individually against our /token endpoint.
=> BCDA-7437: Update sandbox credentials

_includes/build/access_token.html, _includes/build/bcda_credentials.html, _includes/build/bcda_user_guide.html, _includes/build/environment_info.html, _includes/guide/production_environment.html, build.html
https://jira.cms.gov/browse/BCDA-7414
Remove v2 alert, change base64 encryption to "encoding," and reference environments + ip allow list on build page.
The google group gets lots of questions about not receiving responses from the production url before setting up the allow list and credentials. This should help.
Manual verification via inspection. 
=> BCDA-7414: Update Build documentation to reference environments

ops/Jenkinsfile.build_trigger
https://jira.cms.gov/browse/PLT-326
Reference to master branch was changed to main
Github repository master branch renamed to main. changes made to reference main in jenkins instead of master
=> modify reference of  master branch to main

README.md, scripts/build_and_test.sh
N/A
- Did a find-replace for `docker-compose ` to `docker compose `
See https://github.com/orgs/community/discussions/116610 for relevant discussion.
[Stage deployment](https://management.bcda.cms.gov/job/BCDA%20-%20Deploy%20-%20Static%20Site/382/)
=> Update docker-compose commands

_includes/build/access_token.html, _includes/build/attribution_status.html, _includes/build/bcda_v2.html, _includes/build/best_practices_download_speed.html, _includes/build/cancelling_jobs.html, _includes/build/requesting_data_all_three.html, _includes/build/requesting_data_runouts.html, _includes/build/requesting_filtered_data_since_Group.html, _includes/build/requesting_filtered_data_since_Patient.html, _includes/guide/bcda_v2.html, _includes/guide/try_the_api.html
https://jira.cms.gov/browse/BCDA-8391
Standardize dynamic parameters in various example code blocks
Previously we had a mishmash of hardcoded values and substitution representations (eg in one place we would have `/jobs/42` and others `/jobs/{job_id}`).  The goal here was to standardize these.
Went through each page carefully to doublecheck.
=> BCDA-8391 standardize dynamic parameters

_includes/build/request_metadata.html
Update Static Site /Build page to show /metadata response for V2
https://jira.cms.gov/browse/BCDA-8770
Change the sample /metadata response on the Build page to V2 Production (was V1 Sandbox)
Previous
Matches the website content with the latest and most-used BCDA version
=> Update Static Site /Build page to show /metadata response for V2

_pages/get-a-bearer-token.md
https://jira.cms.gov/browse/BCDA-8856
Line 46 surfaces a gitleaks error. [Read the gitleaks docs](https://github.com/gitleaks/gitleaks?tab=readme-ov-file)
I attempted to fix this error with both `#gitleaks:allow` as an in-line comment and with a '.gitleaksignore' file, but since this is a code snippet captured as '{% raw %}' neither of these workarounds were successful.
Therefore, I fixed this my removing two characters in line 46, which prevented gitleaks from recognizing it as a leak. Since this snippet is purely for example purposes, this shouldn't be an issue
=> Get a bearer token page 

_pages/access-claims-data.md
https://jira.cms.gov/browse/BCDA-8857
=> Access claims data page

_pages/api-documentation.md
https://jira.cms.gov/browse/BCDA-8855
=> API Documentation page

_includes/data/bcda_v2_data.html
https://jira.cms.gov/browse/BCDA-8934?src=confmacro
[Fix typo in understanding data page](https://jira.cms.gov/browse/BCDA-8934?src=confmacro)
From Michael Valdes' friction log
=> Fix typo in understanding data page

_data/api-docs-nav.yml, _pages/bcda-data.md, _pages/comparison-bcda-cclf-files.md, _pages/difference-between-v1-v2.md, _pages/filter-claims-data.md, _pages/partially-adjudicated-claims-data.md, _pages/production-access.md, _pages/sitemap.md, _pages/support.md, index.md
https://jira.cms.gov/browse/BCDA-8953
This merge only fixes links. All links now
1. use .html in the address
2. link to the correct page 
3. use the updated URLs
4. have correct internal versus external behavior
Not yet fixed: links to some headings may not behave as expected. This will be addressed in coming changes
=> USWDS redesign: Fix site hyperlink appearance and behavior 

_includes/footer.html, _pages/comparison-bcda-cclf-files.md, _pages/difference-between-v1-v2.md, _pages/get-a-bearer-token.md, _pages/partially-adjudicated-claims-data.md
https://jira.cms.gov/browse/BCDA-8969
https://jira.cms.gov/browse/BCDA-8287
content edits before pm review: 
-reviewed paca guide
-reviewed comparison of bcda cclf 
-reviewed v1 vs. v2 
+ other edits based on feedback so far from greg and karley (more to come)
=> copy edits

_includes/api-docs-side-nav.html, _includes/copy_snippet.html, _includes/footer.html, _includes/head.html, _includes/header.html, _includes/identifier.html, _layouts/api-docs.html, _layouts/base.html, assets/js/tealium-click-events.js
https://jira.cms.gov/browse/BCDA-9055
Adds tealium click event script and data attributes to assign event listeners
Updates analytics to capture various site interactions
Manual QA
=> [BCDA-9055] Add Tealium click events

_pages/get-a-bearer-token.md
https://jira.cms.gov/browse/BCDA-9016
Follow-up PR to mirror changes to main made in https://github.com/CMSgov/bcda-static-site/pull/252
Updated the test credentials, which were just rotated.
The credentials for the sandbox "try me" demo were rotated before they expired. Note that these are exposed secrets in the repo and are intended for the public on the static site.
=> BCDA-9016: Update rotated test credentials for redesign

_pages/api-documentation/filter-claims-data.md
https://jira.cms.gov/browse/BCDA-9183
Reorganizes content on the How Filter Claims Data page
=> [BCDA-9183] Filter Claims content updates

Gemfile.lock, _pages/about.md, _pages/api-documentation.md, _pages/api-documentation/access-claims-data.md, _pages/api-documentation/filter-claims-data.md, _pages/api-documentation/get-a-bearer-token.md, _pages/bcda-data.md, _pages/bcda-data/comparison-bcda-cclf-files.md, _pages/bcda-data/difference-between-v1-v2.html, _pages/bcda-data/partially-adjudicated-claims-data.md, _pages/support.md, index.html
All changes summarized in the purple sticky notes on [Mural](https://app.mural.co/t/ccs9461/m/ccs9461/1747241240315/325c4f995953f086c9c558edac7f7a0c1d9f37fd)
Significant changes were limited to:
- About page now has a new table about PACA + an updated description
- Get a Bearer Token page updated for clarity. Removed some copy + added "Troubleshooting" section. Changes also reflected as suggestions on [content doc](https://docs.google.com/document/d/1xogPTzhEF_kS5cB1zpcFQ82DTBL-umrHqS5At5YM-GQ/edit?usp=sharing) 
- new use case overviews on the homepage
=> Post-research, pre-launch static site updates

_includes/api-docs-side-nav.html, _includes/head.html, _includes/header.html, _pages/about.md, _pages/api-documentation/access-claims-data.md, _pages/bcda-data.md, _pages/bcda-data/comparison-bcda-cclf-files.md, _pages/bcda-data/partially-adjudicated-claims-data.md
https://jira.cms.gov/browse/BCDA-9140
Updates data attributes for tealium event tracking
We manually trigger a number of click events for analytics tracking. This properly configures each event to be correctly triggered depending on the type.
Manual QA
=> [BCDA-9140] Updates Tealium data attributes

index.html
https://jira.cms.gov/browse/BCDA-9333
Resolves a typo Eric spotted in the BCDA homepage
=> BCDA-9333: fix typo on BCDA home page

.github/workflows/deploy.yml
https://jira.cms.gov/browse/BCDA-9350
- fixed an empty arg in the jekyll build when building from main
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
=> BCDA-9350: fix missing arg on main deploy

.github/workflows/pull-request.yml, src/_pages/about.md
https://jira.cms.gov/browse/bcda-9416
Add short note letting customers know when to expect updates to adjudicated claims data to be available via BCDA
Previously we had this information on the website, but it was removed in the website redesign
=> BCDA-9416 Add note on adjudicated claims availability

.github/workflows/pull-request.yml, src/_announcements/open-call-for-bcda-v3-pilot-program.md, src/_announcements/post-connectathon-theres-still-time-to-test-v3.md, src/_announcements/try-the-api-at-the-2025-hl7-fhir-connectathon.md, src/index.html
[BCDA-9389](https://jira.cms.gov/browse/BCDA-9389)
Adds v3 pilot announcement content to site
Manual QA
=> BCDA-9389 Add V3 pilot announcement content
